// AUTOGENERATED FILE. DO NOT MODIFY.
// Generated via `npm run gen-shmem`

// Instance: 418408b6-fd52-4d9e-b93a-0d031e7d27c0

#pragma once
#include <stdint.h>

#define FIRMWARE_IDENT 192

struct Data {
  uint16_t ioConfig;
  uint8_t firmwareIdent;
  uint8_t status;
  bool heartbeat;
  uint8_t builtinConfig;
  bool builtinDioValues[4];
  int16_t extIoValues[5];
  uint16_t analog[2];
  int16_t pinkMotor;
  int16_t ringMotor;
  uint16_t batteryMillivolts;
  bool resetLeftEncoder;
  bool resetRightEncoder;
  int16_t leftEncoder;
  int16_t rightEncoder;
};
