// AUTOGENERATED FILE. DO NOT MODIFY.
// Generated via `npm run gen-shmem`

// Instance: 30ff0620-60d4-4a64-9ea0-c815b4429529

#pragma once
#include <stdint.h>

#define FIRMWARE_IDENT 41

struct Data {
  uint16_t ioConfig;
  uint8_t firmwareIdent;
  uint8_t status;
  bool heartbeat;
  uint8_t builtinConfig;
  bool builtinDioValues[4];
  int16_t extIoValues[5];
  uint16_t analog[2];
  int16_t pinkMotor;
  int16_t ringMotor;
  int16_t middleMotor;
  int16_t indexMotor;
  uint16_t batteryMillivolts;
  bool resetPinkEncoder;
  bool resetRingEncoder;
  bool resetMiddleEncoder;
  bool resetIndexEncoder;
  int16_t pinkEncoder;
  int16_t ringEncoder;
  int16_t middleEncoder;
  int16_t indexEncoder;
};
