// AUTOGENERATED FILE. DO NOT MODIFY.
// Generated via `npm run gen-shmem`

// Instance: 30ff0620-60d4-4a64-9ea0-c815b4429529

export const FIRMWARE_IDENT: number = 41;

export enum ShmemDataType {
    BOOL,
    UINT8_T,
    INT8_T,
    UINT16_T,
    INT16_T,
}

export interface ShmemElementDefinition {
    offset: number;
    type: ShmemDataType;
    arraySize?: number;
}

const shmemBuffer: {[key: string]: ShmemElementDefinition} = {
    ioConfig: { offset: 0, type: ShmemDataType.UINT16_T},
    firmwareIdent: { offset: 2, type: ShmemDataType.UINT8_T},
    status: { offset: 3, type: ShmemDataType.UINT8_T},
    heartbeat: { offset: 4, type: ShmemDataType.BOOL},
    builtinConfig: { offset: 5, type: ShmemDataType.UINT8_T},
    builtinDioValues: { offset: 6, type: ShmemDataType.BOOL, arraySize: 4},
    extIoValues: { offset: 10, type: ShmemDataType.INT16_T, arraySize: 5},
    analog: { offset: 20, type: ShmemDataType.UINT16_T, arraySize: 2},
    pinkMotor: { offset: 24, type: ShmemDataType.INT16_T},
    ringMotor: { offset: 26, type: ShmemDataType.INT16_T},
    middleMotor: { offset: 28, type: ShmemDataType.INT16_T},
    indexMotor: { offset: 30, type: ShmemDataType.INT16_T},
    batteryMillivolts: { offset: 32, type: ShmemDataType.UINT16_T},
    resetPinkEncoder: { offset: 34, type: ShmemDataType.BOOL},
    resetRingEncoder: { offset: 35, type: ShmemDataType.BOOL},
    resetMiddleEncoder: { offset: 36, type: ShmemDataType.BOOL},
    resetIndexEncoder: { offset: 37, type: ShmemDataType.BOOL},
    pinkEncoder: { offset: 38, type: ShmemDataType.INT16_T},
    ringEncoder: { offset: 40, type: ShmemDataType.INT16_T},
    middleEncoder: { offset: 42, type: ShmemDataType.INT16_T},
    indexEncoder: { offset: 44, type: ShmemDataType.INT16_T},
};

export default Object.freeze(shmemBuffer);
